import { Repository, CompetitionLevel, ActivityLevel, AIDomain, ContributionDifficultyLevel } from './types';

export const FALLBACK_REPOS: Repository[] = [
  {
    id: 10270250,
    name: 'react',
    full_name: 'facebook/react',
    owner: {
      login: 'facebook',
      avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4',
      html_url: 'https://github.com/facebook'
    },
    html_url: 'https://github.com/facebook/react',
    description: 'The library for web and native user interfaces',
    stargazers_count: 213000,
    watchers_count: 6700,
    forks_count: 45000,
    open_issues_count: 900,
    language: 'JavaScript',
    topics: ['declarative', 'frontend', 'javascript', 'library', 'react', 'ui'],
    created_at: '2013-05-24T16:15:54Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    default_branch: 'main',
    archived: false,
    disabled: false,
    has_issues: true,
    has_projects: true,
    has_wiki: true,
    has_pages: true,
    has_downloads: true,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit'
    },
    competition_level: CompetitionLevel.VERY_HIGH,
    activity_level: ActivityLevel.HIGHEST,
    ai_domain: AIDomain.OTHER,
    contribution_difficulty: ContributionDifficultyLevel.EXPERT,
    last_analyzed: new Date().toISOString(),
    contributor_count: 1600,
    recent_commits: 50,
    issue_response_rate: 95,
    documentation_score: 98,
    good_first_issues_count: 5
  },
  {
    id: 11730342,
    name: 'vue',
    full_name: 'vuejs/vue',
    owner: {
      login: 'vuejs',
      avatar_url: 'https://avatars.githubusercontent.com/u/6128107?v=4',
      html_url: 'https://github.com/vuejs'
    },
    html_url: 'https://github.com/vuejs/vue',
    description: '🖖 Vue.js is a progressive, incrementally-adoptable JavaScript framework for building UI on the web.',
    stargazers_count: 205000,
    watchers_count: 6000,
    forks_count: 33000,
    open_issues_count: 500,
    language: 'TypeScript',
    topics: ['framework', 'frontend', 'javascript', 'vue'],
    created_at: '2013-07-29T03:24:51Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    default_branch: 'main',
    archived: false,
    disabled: false,
    has_issues: true,
    has_projects: true,
    has_wiki: true,
    has_pages: true,
    has_downloads: true,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit'
    },
    competition_level: CompetitionLevel.HIGH,
    activity_level: ActivityLevel.HIGH,
    ai_domain: AIDomain.OTHER,
    contribution_difficulty: ContributionDifficultyLevel.ADVANCED,
    last_analyzed: new Date().toISOString(),
    contributor_count: 400,
    recent_commits: 30,
    issue_response_rate: 90,
    documentation_score: 95,
    good_first_issues_count: 12
  },
  {
    id: 70107786,
    name: 'next.js',
    full_name: 'vercel/next.js',
    owner: {
      login: 'vercel',
      avatar_url: 'https://avatars.githubusercontent.com/u/14985020?v=4',
      html_url: 'https://github.com/vercel'
    },
    html_url: 'https://github.com/vercel/next.js',
    description: 'The React Framework',
    stargazers_count: 112000,
    watchers_count: 1400,
    forks_count: 25000,
    open_issues_count: 2000,
    language: 'JavaScript',
    topics: ['blog', 'browser', 'compiler', 'components', 'hybrid', 'nextjs', 'node', 'react', 'server-rendering', 'ssg', 'static', 'static-site-generator', 'universal', 'vercel'],
    created_at: '2016-10-05T23:32:51Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    default_branch: 'canary',
    archived: false,
    disabled: false,
    has_issues: true,
    has_projects: true,
    has_wiki: false,
    has_pages: false,
    has_downloads: true,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit'
    },
    competition_level: CompetitionLevel.VERY_HIGH,
    activity_level: ActivityLevel.HIGHEST,
    ai_domain: AIDomain.OTHER,
    contribution_difficulty: ContributionDifficultyLevel.EXPERT,
    last_analyzed: new Date().toISOString(),
    contributor_count: 2800,
    recent_commits: 150,
    issue_response_rate: 85,
    documentation_score: 92,
    good_first_issues_count: 8
  },
  {
    id: 28457823,
    name: 'freeCodeCamp',
    full_name: 'freeCodeCamp/freeCodeCamp',
    owner: {
      login: 'freeCodeCamp',
      avatar_url: 'https://avatars.githubusercontent.com/u/9892522?v=4',
      html_url: 'https://github.com/freeCodeCamp'
    },
    html_url: 'https://github.com/freeCodeCamp/freeCodeCamp',
    description: 'freeCodeCamp.org\'s open-source codebase and curriculum. Learn to code for free.',
    stargazers_count: 375000,
    watchers_count: 8500,
    forks_count: 33000,
    open_issues_count: 150,
    language: 'TypeScript',
    topics: ['careers', 'certification', 'community', 'curriculum', 'education', 'freecodecamp', 'hacktoberfest', 'javascript', 'learn-to-code', 'math', 'nodejs', 'nonprofits', 'programming', 'react', 'teachers'],
    created_at: '2014-12-24T17:49:19Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    default_branch: 'main',
    archived: false,
    disabled: false,
    has_issues: true,
    has_projects: true,
    has_wiki: false,
    has_pages: false,
    has_downloads: true,
    license: {
      key: 'bsd-3-clause',
      name: 'BSD 3-Clause "New" or "Revised" License',
      spdx_id: 'BSD-3-Clause',
      url: 'https://api.github.com/licenses/bsd-3-clause'
    },
    competition_level: CompetitionLevel.MEDIUM,
    activity_level: ActivityLevel.HIGH,
    ai_domain: AIDomain.OTHER,
    contribution_difficulty: ContributionDifficultyLevel.BEGINNER,
    last_analyzed: new Date().toISOString(),
    contributor_count: 4500,
    recent_commits: 80,
    issue_response_rate: 98,
    documentation_score: 99,
    good_first_issues_count: 25
  },
  {
    id: 177736533,
    name: '996.ICU',
    full_name: '996icu/996.ICU',
    owner: {
      login: '996icu',
      avatar_url: 'https://avatars.githubusercontent.com/u/48942249?v=4',
      html_url: 'https://github.com/996icu'
    },
    html_url: 'https://github.com/996icu/996.ICU',
    description: 'Repo for counting stars and contributing. Press F to pay respects to glorious developers.',
    stargazers_count: 267000,
    watchers_count: 4200,
    forks_count: 21000,
    open_issues_count: 20000,
    language: null,
    topics: [],
    created_at: '2019-03-26T07:31:14Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    default_branch: 'master',
    archived: false,
    disabled: false,
    has_issues: true,
    has_projects: false,
    has_wiki: false,
    has_pages: false,
    has_downloads: true,
    license: {
      key: 'other',
      name: 'Other',
      spdx_id: 'NOASSERTION',
      url: ''
    },
    competition_level: CompetitionLevel.LOW,
    activity_level: ActivityLevel.LOW,
    ai_domain: AIDomain.OTHER,
    contribution_difficulty: ContributionDifficultyLevel.BEGINNER,
    last_analyzed: new Date().toISOString(),
    contributor_count: 500,
    recent_commits: 0,
    issue_response_rate: 0,
    documentation_score: 50,
    good_first_issues_count: 0
  },
  {
    id: 13491895,
    name: 'free-programming-books',
    full_name: 'EbookFoundation/free-programming-books',
    owner: {
      login: 'EbookFoundation',
      avatar_url: 'https://avatars.githubusercontent.com/u/14127308?v=4',
      html_url: 'https://github.com/EbookFoundation'
    },
    html_url: 'https://github.com/EbookFoundation/free-programming-books',
    description: '📚 Freely available programming books',
    stargazers_count: 300000,
    watchers_count: 9800,
    forks_count: 58000,
    open_issues_count: 40,
    language: null,
    topics: ['books', 'education', 'list', 'resource'],
    created_at: '2013-10-11T06:50:37Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    default_branch: 'main',
    archived: false,
    disabled: false,
    has_issues: true,
    has_projects: false,
    has_wiki: false,
    has_pages: false,
    has_downloads: true,
    license: {
      key: 'cc-by-4.0',
      name: 'Creative Commons Attribution 4.0 International',
      spdx_id: 'CC-BY-4.0',
      url: 'https://api.github.com/licenses/cc-by-4.0'
    },
    competition_level: CompetitionLevel.LOW,
    activity_level: ActivityLevel.MEDIUM,
    ai_domain: AIDomain.OTHER,
    contribution_difficulty: ContributionDifficultyLevel.BEGINNER,
    last_analyzed: new Date().toISOString(),
    contributor_count: 2500,
    recent_commits: 20,
    issue_response_rate: 80,
    documentation_score: 90,
    good_first_issues_count: 10
  },
  {
    id: 21737465,
    name: 'awesome',
    full_name: 'sindresorhus/awesome',
    owner: {
      login: 'sindresorhus',
      avatar_url: 'https://avatars.githubusercontent.com/u/170270?v=4',
      html_url: 'https://github.com/sindresorhus'
    },
    html_url: 'https://github.com/sindresorhus/awesome',
    description: '😎 Awesome lists about all kinds of interesting topics',
    stargazers_count: 275000,
    watchers_count: 7500,
    forks_count: 26000,
    open_issues_count: 50,
    language: null,
    topics: ['awesome', 'awesome-list', 'lists', 'resources', 'unicorns'],
    created_at: '2014-07-11T13:42:37Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    default_branch: 'main',
    archived: false,
    disabled: false,
    has_issues: true,
    has_projects: false,
    has_wiki: false,
    has_pages: true,
    has_downloads: true,
    license: {
      key: 'cc0-1.0',
      name: 'Creative Commons Zero v1.0 Universal',
      spdx_id: 'CC0-1.0',
      url: 'https://api.github.com/licenses/cc0-1.0'
    },
    competition_level: CompetitionLevel.LOW,
    activity_level: ActivityLevel.MEDIUM,
    ai_domain: AIDomain.OTHER,
    contribution_difficulty: ContributionDifficultyLevel.BEGINNER,
    last_analyzed: new Date().toISOString(),
    contributor_count: 500,
    recent_commits: 10,
    issue_response_rate: 70,
    documentation_score: 85,
    good_first_issues_count: 5
  },
  {
    id: 54346799,
    name: 'public-apis',
    full_name: 'public-apis/public-apis',
    owner: {
      login: 'public-apis',
      avatar_url: 'https://avatars.githubusercontent.com/u/51121562?v=4',
      html_url: 'https://github.com/public-apis'
    },
    html_url: 'https://github.com/public-apis/public-apis',
    description: 'A collective list of free APIs',
    stargazers_count: 265000,
    watchers_count: 6000,
    forks_count: 30000,
    open_issues_count: 200,
    language: 'Python',
    topics: ['api', 'apis', 'dataset', 'development', 'free', 'list', 'lists', 'open-source', 'public-apis', 'resources', 'software'],
    created_at: '2016-03-20T23:49:42Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    default_branch: 'master',
    archived: false,
    disabled: false,
    has_issues: true,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    has_downloads: true,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit'
    },
    competition_level: CompetitionLevel.MEDIUM,
    activity_level: ActivityLevel.HIGH,
    ai_domain: AIDomain.OTHER,
    contribution_difficulty: ContributionDifficultyLevel.BEGINNER,
    last_analyzed: new Date().toISOString(),
    contributor_count: 1200,
    recent_commits: 40,
    issue_response_rate: 60,
    documentation_score: 80,
    good_first_issues_count: 15
  },
  {
    id: 85077558,
    name: 'developer-roadmap',
    full_name: 'kamranahmedse/developer-roadmap',
    owner: {
      login: 'kamranahmedse',
      avatar_url: 'https://avatars.githubusercontent.com/u/1335446?v=4',
      html_url: 'https://github.com/kamranahmedse'
    },
    html_url: 'https://github.com/kamranahmedse/developer-roadmap',
    description: 'Interactive roadmaps, guides and other educational content to help developers grow in their careers.',
    stargazers_count: 255000,
    watchers_count: 7000,
    forks_count: 35000,
    open_issues_count: 600,
    language: 'TypeScript',
    topics: ['career', 'computer-science', 'developer-roadmap', 'devops', 'engineering', 'frontend', 'guide', 'roadmap', 'study-plan'],
    created_at: '2017-03-15T13:45:52Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    default_branch: 'master',
    archived: false,
    disabled: false,
    has_issues: true,
    has_projects: true,
    has_wiki: false,
    has_pages: true,
    has_downloads: true,
    license: {
      key: 'cc-by-4.0',
      name: 'Creative Commons Attribution 4.0 International',
      spdx_id: 'CC-BY-4.0',
      url: 'https://api.github.com/licenses/cc-by-4.0'
    },
    competition_level: CompetitionLevel.MEDIUM,
    activity_level: ActivityLevel.HIGH,
    ai_domain: AIDomain.OTHER,
    contribution_difficulty: ContributionDifficultyLevel.INTERMEDIATE,
    last_analyzed: new Date().toISOString(),
    contributor_count: 800,
    recent_commits: 50,
    issue_response_rate: 85,
    documentation_score: 95,
    good_first_issues_count: 10
  }
];
